apiVersion: apps/v1
kind: Deployment
metadata:
  name: apptwo
  labels:
    app: apptwo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apptwo
  template:
    metadata:
      labels:
        app: apptwo
    spec:
      containers:
      - name: nginx
        image: paulbouwer/hello-kubernetes:1.10.1
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hello from app2.
---
apiVersion: v1
kind: Service
metadata:
  name: apptwo
spec:
  selector:
    app: apptwo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080