# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"
    config.vbguest.installer_options = { allow_kernel_upgrade: true }
    config.vm.box_check_update = false

    # vagrant plugin install vagrant-vbguest

    config.vm.define "ybollesS" do |control|
        control.vm.hostname = "ybollesS"
        control.vm.network :public_network, ip: "192.168.42.110"
        control.vm.synced_folder "./shared", "/vagrant_shared"
        control.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--name", "ybollesS"]
            vb.customize ["modifyvm", :id, "--memory", "1024"]
            vb.customize ["modifyvm", :id, "--cpus", "1"]
        end
        control.vm.provision "shell", path: "./Scripts/ybollesS.sh"
      end
end
