apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil42
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/issamelferkh/ybolles_config.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
