apiVersion: apps/v1
kind: Deployment
metadata:
  name: appthree
  labels:
    app: appthree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appthree
  template:
    metadata:
      labels:
        app: appthree
    spec:
      containers:
      - name: nginx
        image: paulbouwer/hello-kubernetes:1.10.1
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hello from app3.
---
apiVersion: v1
kind: Service
metadata:
  name: appthree
spec:
  selector:
    app: appthree
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080