apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: "app1.com"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: appone
            port:
              number: 80
  - host: "app2.com"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: apptwo
            port:
              number: 80
  - host: "app3.com"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: appthree
            port:
              number: 80